name: datalib
description: A dart libary for data science and statistical calculations
version: 0.0.1
homepage: https://github.com/FATIHISILGAN/

repository: https://github.com/FATIHISILGAN/dataLib/

documentation: https://github.com/FATIHISILGAN/dataLib/

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

